# Liste des mots du pendu
liste_mots = [
    "armoire",
    "boucle",
    "buisson",
    "bureau",
    "chaise",
    "carton",
    "couteau",
    "fichier",
    "garage",
    "glace",
    "journal",
    "kiwi",
    "lampe",
    "liste",
    "montagne",
    "remise",
    "sandale",
    "taxi",
    "vampire",
    "volant",
]

#dico des stades du pendu
chances = {  8:["____ ",
                "|/",
                "|",
                "|",
                "|",
                "|____"],
             7:["____ ",
                "|/ |",
                "|",
                "|",
                "|",
                "|____"],
             6:["____ ",
                "|/",
                "|",
                "|",
                "|",
                "|____"],
             5:["____ ",
                "|/",
                "|",
                "|",
                "|",
                "|____"],
             4:["____ ",
                "|/",
                "|",
                "|",
                "|",
                "|____"],
             3:["____ ",
                "|/",
                "|",
                "|",
                "|",
                "|____"],
             2:["____ ",
                "|/",
                "|",
                "|",
                "|",
                "|____"],
             1:["____ ",
                "|/",
                "|",
                "|",
                "|",
                "|____"],
             0:["____ ",
                "|/ | ",
                "| \\o/",
                "|  | ",
                "| / \\",
                "|____"]
}

# fonction qui affiche le pendu en fonction du nombre de chance restante


# fonction qui masque les lettre sauf celles deja trouvee passee en parametre
